pub mod notify_opponent_to_energy_usage;
pub mod notify_opponent_to_energy_boost;
pub mod notify_opponent_to_unit_deploy;
pub mod notify_opponent_to_draw_support_usage;
pub mod notify_opponent_search_support_usage;
pub mod notify_opponent_to_instant_death_item_alternatives_usage;