pub mod target_death_item_request_form;
pub mod add_field_energy_with_field_unit_health_point_item_request_form;
pub mod catastrophic_damage_item_request_form;
pub mod multiple_target_damage_by_field_unit_death_item_request_form;
pub mod remove_opponent_field_unit_energy_item_request_form;
pub mod remove_opponent_field_energy_item_request_form;