pub mod add_unit_to_game_field_response;
pub mod attach_single_energy_to_unit_index_response;
pub mod attach_multiple_energy_to_unit_index_response;
pub mod find_target_unit_id_by_index_response;
pub mod apply_damage_to_target_unit_index_response;
pub mod apply_instant_death_to_target_unit_index_response;