use futures::poll;

pub mod notice_boost_energy_to_specific_unit_request;
pub mod notice_draw_card_request;
pub mod notice_search_card_request;
pub mod notice_remove_field_energy_by_using_hand_card_request;
pub mod notice_remove_energy_of_specific_unit_by_using_hand_card_request;
pub mod notice_apply_damage_to_specific_unit_by_using_hand_card_request;
pub mod notice_apply_damage_to_every_unit_by_using_hand_card_request;
pub mod notice_attach_energy_to_specific_unit_by_using_hand_card_request;
pub mod notice_instant_death_of_specific_unit_by_using_hand_card_request;
pub mod notice_use_hand_card_request;