pub mod account_request_generator;
pub mod request_generator;
pub mod session_request_generator;
pub mod client_program_request_generator;
pub mod battle_wait_queue_request_generator;
pub mod account_deck_request_generator;
pub mod battle_ready_account_hash_request_generator;
pub mod account_deck_card_request_generator;
pub mod shop_request_generator;
pub mod what_is_the_room_number_request_generator;
pub mod check_battle_prepare_request_generator;
pub mod account_point_request_generator;
pub mod game_deck_card_list_request_generator;
pub mod account_card_request_generator;
pub mod deploy_unit_request_form_generator;
pub mod attach_general_energy_card_request_form_generator;
pub mod mulligan_request_generator;
pub mod energy_boost_support_request_form_generator;
pub mod general_draw_support_request_form_generator;
pub mod search_unit_support_request_form_generator;
pub mod opponent_field_energy_remove_support_request_form_generator;
pub mod first_turn_decision_wait_queue_request_form_generator;
pub mod first_turn_decision_request_generator;
pub mod game_card_item_request_form_generator;


