pub mod account_request_generator;
pub mod request_generator;
pub mod session_request_generator;
pub mod client_program_request_generator;
pub mod battle_wait_queue_request_generator;
pub mod account_deck_request_generator;
pub mod battle_ready_account_hash_request_generator;
pub mod account_deck_card_request_generator;
pub mod shop_request_generator;
pub mod what_is_the_room_number_request_generator;
pub mod check_battle_prepare_request_generator;
pub mod account_point_request_generator;
pub mod game_deck_card_list_request_generator;
mod account_card_request_generator;
mod use_hand_unit_request_generator;

