pub mod notify_opponent_hand_to_unit_action_response;
pub mod notify_to_opponent_what_you_do_response;
pub mod notify_to_opponent_you_use_energy_card_response;
pub mod notify_to_opponent_you_use_energy_boost_card_response;