pub mod generate_use_energy_card_to_my_specific_unit_data_request;
pub mod generate_use_field_energy_to_my_specific_unit_data_request;
pub mod generate_use_support_card_to_boost_energy_to_my_specific_unit_data_request;
pub mod generate_use_support_card_to_draw_my_deck_data_request;
pub mod generate_use_support_card_to_search_unit_from_my_deck_data_request;
pub mod generate_use_support_card_to_remove_your_field_energy_data_request;
pub mod generate_instant_death_of_your_specific_unit_data_request;
pub mod generate_use_item_card_for_damage_of_your_specific_unit_data_request;
