pub mod deploy_targeting_attack_passive_skill_response_form;
pub mod deploy_non_targeting_attack_passive_skill_response_form;
pub mod turn_start_targeting_attack_passive_skill_response_form;
pub mod turn_start_non_targeting_attack_passive_skill_response_form;